### ISSUE TITLE
checkSupport returns false for .JPG href

### ISSUE THREAD

**Issue by justinholtweb** [rqrauhvmra/Tobi#36]
My assets collection has mixed filetypes including an image asset using .JPG as file extension. On line 124 of tobi.js the checkSupport method is returning false due to a failed match with the check el.href.match(/\.(png|jpe?g|tiff|tif|gif|bmp|webp|svg|ico)$/) for this asset. Does TOBI require lowercase file extensions?

**Comment by midzer** [comment]
Normally this should have been fixed by https://github.com/rqrauhvmra/Tobi/pull/28

**Comment by justinholtweb** [comment]
hmm wonder why it's still occurring for me? I'm running 1.8.1 from npm.

**Comment by justinholtweb** [comment]
Oh wait, is this only merged to 1.8.2?

**Comment by midzer** [comment]
Yeah, looks like:

> rqrauhvmra merged commit 28dcff9 into rqrauhvmra:1.8.2 on Feb 21

**Comment by justinholtweb** [comment]
Thanks so much for the help! I'll await that release or 2.0 whichever comes first!
